# Generated by Django 3.2 on 2022-07-30 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_codigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='productor',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
    ]
