# Generated by Django 3.2 on 2022-08-02 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_productimage_image1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='createcreatedAt',
            new_name='createdAt',
        ),
    ]
