# Generated by Django 3.2 on 2022-08-04 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_auto_20220804_0245'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cantidad',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
        ),
    ]
